# Generated by Django 5.1 on 2024-08-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_created_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Study', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category'),
        ),
    ]
