# Generated by Django 5.1 on 2024-08-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
